# -*- coding: utf-8 -*-
"""gallery_images_clustering_efficient_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13B2q0jxYXmg9v9oPgj8QdzW4UoPLJ3RE

# Image Clustering & Android Export Pipeline

This notebook processes a folder of images to group them by visual similarity, assigns semantic names using CLIP, and exports an optimized model for Android.

### 📑 Table of Contents
1. **Phase 1:** [Environment Setup](#phase1)
2. **Phase 2:** [Feature Extraction (DINOv2)](#phase2)
3. **Phase 3:** [Clustering & Optimization](#phase3)
4. **Phase 4:** [Quality Analysis & Visualization](#phase4)
5. **Phase 5:** [Semantic Naming & Metadata](#phase5)
6. **Phase 6:** [ONNX Export & Mobile Optimization](#phase6)

<a name="phase1"></a>
## Phase 1: Environment Setup and Model Loading
In this phase, we install dependencies, verify GPU acceleration, and perform a sanity check on the DINOv2 model.

# Image Clustering & Android Export Pipeline
This notebook processes a folder of images to group them by visual similarity, assigns semantic names using CLIP, and exports a optimized model for Android.

### Phases Covered
*   **Phase 1:** Environment Setup and Model Loading
*   **Phase 2:** Feature Extraction (DINOv2)
*   **Phase 3:** Dimensionality Reduction and Clustering
*   **Phase 4:** Quality Analysis and Visualization
*   **Phase 5:** Semantic Naming and Metadata Generation
*   **Phase 6:** ONNX Export and Mobile Optimization

### **Cell 1 — Install Dependencies**
* This cell installs necessary libraries for machine learning, image processing, and model export.
* It expects an active internet connection to download packages from PyPI.
* It outputs a successful installation message for libraries like Torch and Transformers.
"""

!pip install torch torchvision transformers onnx onnxruntime \ scikit-learn umap-learn matplotlib seaborn \ Pillow numpy scipy

"""### **Cell 2 — GPU Verification**
* This cell checks if a graphics processor (GPU) is available to speed up processing.
* It outputs the name of the detected GPU, such as the Tesla T4.
* This helps confirm the environment is ready for heavy computation.
"""

import torch
print(torch.cuda.is_available())        # Should print True on Colab free T4
print(torch.cuda.get_device_name(0))    # Should print Tesla T4

"""### **Cell 3 — Sanity Check Model**
* This cell loads the DINOv2 model and runs it on a single test image.
* It expects at least one image to exist in the test folder.
* It outputs the shape of the resulting embedding to confirm the model is working.
"""

from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import torch

processor = AutoImageProcessor.from_pretrained('facebook/dinov2-small')
model = AutoModel.from_pretrained('facebook/dinov2-small')
model.eval()

# Quick sanity check on one image
img = Image.open('/content/test_images/1.jpg').convert('RGB')
inputs = processor(images=img, return_tensors='pt')
with torch.no_grad():
    outputs = model(**inputs)

# CLS token = global image embedding (384-dim for DINOv2-small)
embedding = outputs.last_hidden_state[:, 0, :]
print("Embedding shape:", embedding.shape)   # Should print torch.Size([1, 384])
print("Model loaded and working ✓")

"""### **Cell 4 — Parameter & Size Analysis**
* This cell calculates the total number of parameters in the DINOv2-small model.
* It estimates the file size of the model to ensure it is small enough for mobile apps.
* It outputs the parameter count and an approximate MB size.
"""

import os
# DINOv2-small should be ~85MB — confirm it's feasible for mobile
param_count = sum(p.numel() for p in model.parameters())
print(f"Parameters: {param_count:,}")       # ~22M params
print(f"Approx size: {param_count * 4 / 1e6:.1f} MB")  # ~85MB

"""### **Cell 5 — Load Production Model**
* This cell initializes the DINOv2 model and image processor on the best available hardware.
* It prepares the model for high-speed feature extraction in 'eval' mode.
* It outputs a confirmation that the model is ready.

<a name="phase2"></a>
## Phase 2: Feature Extraction (DINOv2)
Here we extract visual 'fingerprints' for every image in the dataset using the DINOv2-small transformer.
"""

import os
import torch
import numpy as np
from PIL import Image
from transformers import AutoImageProcessor, AutoModel
from pathlib import Path

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

processor = AutoImageProcessor.from_pretrained('facebook/dinov2-small')
model = AutoModel.from_pretrained('facebook/dinov2-small')
model = model.to(device)
model.eval()
print("Model ready ✓")

"""### **Cell 6 — Validate Image Folder**
* This cell scans a specific folder to find and verify compatible image files.
* It expects a folder path containing JPG, PNG, or WebP files.
* It outputs a list of valid image paths and reports any corrupted files found.
"""

SUPPORTED_FORMATS = {'.jpg', '.jpeg', '.png', '.webp', '.bmp'}
IMAGE_FOLDER = '/content/test_images'

def load_valid_images(folder):
    valid = []
    skipped = []
    for f in sorted(Path(folder).iterdir()):
        if f.suffix.lower() in SUPPORTED_FORMATS:
            try:
                img = Image.open(f).convert('RGB')
                img.verify()
                valid.append(str(f))
            except Exception as e:
                skipped.append((f.name, str(e)))
    print(f"Valid images: {len(valid)}")
    if skipped:
        print(f"Skipped {len(skipped)} corrupted files: {[s[0] for s in skipped]}")
    return valid

image_paths = load_valid_images(IMAGE_FOLDER)

"""### **Cell 7 — Single Embedding Logic**
* This cell defines a function to extract a balanced foreground and background embedding from an image.
* It uses the 'alpha' parameter to adjust the balance between the main subject and the scene.
* It outputs a 384-dimensional numerical vector representing the image.
"""

def extract_embedding(image_path, alpha=0.5):
    """
    Extracts a combined FG/BG embedding from one image.

    alpha controls the FG/BG balance:
      0.0 = pure CLS token (global scene / background)
      1.0 = pure patch average (foreground objects)
      0.5 = equal blend (default — recommended)
    """
    img = Image.open(image_path).convert('RGB')
    inputs = processor(images=img, return_tensors='pt')
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    tokens = outputs.last_hidden_state  # shape: [1, 257, 384]
                                        # token 0 = CLS, tokens 1-256 = patches

    cls_token   = tokens[:, 0, :]       # [1, 384] — global/BG signal
    patch_tokens = tokens[:, 1:, :]     # [1, 256, 384] — patch/FG signal
    patch_avg   = patch_tokens.mean(dim=1)  # [1, 384]

    # Weighted combination
    combined = (1 - alpha) * cls_token + alpha * patch_avg  # [1, 384]

    # L2 normalize for cosine similarity later
    combined = torch.nn.functional.normalize(combined, dim=-1)

    return combined.squeeze().cpu().numpy()  # [384]


# Quick test on first image
test_emb = extract_embedding(image_paths[0])
print(f"Single embedding shape: {test_emb.shape}")   # Should be (384,)
print(f"Norm (should be ~1.0): {np.linalg.norm(test_emb):.4f}")

"""### **Cell 8 — Batch Feature Extraction**
* This cell runs the extraction logic on every image found in your folder.
* It expects the list of verified image paths from the previous steps.
* It outputs a large numerical matrix containing the fingerprints for all images.

<a name="phase4"></a>
## Phase 4: Quality Analysis and Visualization
This phase calculates Silhouette scores to verify cluster quality and generates 2D maps and image grids for review.
"""

from tqdm import tqdm

def extract_all_embeddings(paths, alpha=0.5):
    embeddings = []
    failed = []

    for path in tqdm(paths, desc="Extracting embeddings"):
        try:
            emb = extract_embedding(path, alpha=alpha)
            embeddings.append(emb)
        except Exception as e:
            print(f"Failed: {Path(path).name} — {e}")
            failed.append(path)
            embeddings.append(np.zeros(384))  # placeholder to keep index alignment

    embeddings = np.array(embeddings)  # shape: [N, 384]
    print(f"\nDone. Embeddings matrix: {embeddings.shape}")
    print(f"Failed: {len(failed)}")
    return embeddings, failed

embeddings, failed = extract_all_embeddings(image_paths, alpha=0.5)

"""### **Cell 9 — Save Extraction Progress**
* This cell saves the extracted data to files on the local disk to prevent data loss.
* It saves the numerical matrix as a '.npy' file and the paths as a '.txt' file.
* It outputs a confirmation of the file shapes and verification of data integrity.
"""

np.save('/content/embeddings.npy', embeddings)

# Save path list too — keeps index alignment with embeddings
with open('/content/image_paths.txt', 'w') as f:
    f.write('\n'.join(image_paths))

print("Saved embeddings.npy and image_paths.txt ✓")
print(f"Matrix shape: {embeddings.shape}")
print(f"Any NaN: {np.isnan(embeddings).any()}")
print(f"Any zero rows: {(embeddings == 0).all(axis=1).sum()} (these are failed images)")

"""### **Cell 10 — Initial Similarity Test**
* This cell calculates the mathematical similarity between the first few images in your set.
* It expects the saved embedding matrix from the previous cell.
* It outputs the names of the most similar images for the first three items.
"""

from sklearn.metrics.pairwise import cosine_similarity

# Pick first image and find its top 3 most similar
sim_matrix = cosine_similarity(embeddings)
np.fill_diagonal(sim_matrix, 0)  # exclude self

for i in range(min(3, len(image_paths))):
    top3_idx = sim_matrix[i].argsort()[-3:][::-1]
    print(f"\n{Path(image_paths[i]).name} most similar to:")
    for j in top3_idx:
        print(f"  → {Path(image_paths[j]).name}  (similarity: {sim_matrix[i][j]:.3f})")

"""### **Cell 11 — Clean Data for Clustering**
* This cell reloads the data and removes any failed or empty entries.
* It ensures that only valid images with successful fingerprints are sent to the clustering step.
* It outputs the final count of images ready for grouping.

<a name="phase3"></a>
## Phase 3: Dimensionality Reduction and Clustering
We compress the 384-dimensional embeddings into 32 dimensions using UMAP to improve the performance of the K-Means clustering algorithm.
"""

import numpy as np
from pathlib import Path

embeddings = np.load('/content/embeddings.npy')

with open('/content/image_paths.txt', 'r') as f:
    image_paths = [line.strip() for line in f.readlines()]

print(f"Embeddings: {embeddings.shape}")
print(f"Images: {len(image_paths)}")

# Remove any failed zero-rows from Phase 2
valid_mask = ~(embeddings == 0).all(axis=1)
embeddings = embeddings[valid_mask]
image_paths = [p for p, v in zip(image_paths, valid_mask) if v]
print(f"Valid after filtering: {embeddings.shape[0]} images")

"""### **Cell 12 — UMAP Dimensionality Reduction**
* This cell compresses the 384-dimensional data into 32 dimensions for better clustering results.
* It uses the UMAP algorithm with a 'cosine' metric to preserve visual relationships.
* It outputs two versions of the data: one for calculations and one 2D version for mapping.
"""

import umap

print("Running UMAP reduction (384 → 32 dims)...")
reducer = umap.UMAP(
    n_components=32,       # compress to 32 dims for clustering
    n_neighbors=15,        # local neighborhood size
    min_dist=0.0,          # tighter clusters (0.0 = best for clustering use)
    metric='cosine',       # matches our L2-normalized embeddings
    random_state=42
)

embeddings_32d = reducer.fit_transform(embeddings)
print(f"Reduced shape: {embeddings_32d.shape}")   # [N, 32]

# Also reduce to 2D separately just for visualization later
reducer_2d = umap.UMAP(
    n_components=2,
    n_neighbors=15,
    min_dist=0.05,
    metric='cosine',
    random_state=42
)
embeddings_2d = reducer_2d.fit_transform(embeddings)
print(f"2D shape for viz: {embeddings_2d.shape}")  # [N, 2]

np.save('/content/embeddings_32d.npy', embeddings_32d)
np.save('/content/embeddings_2d.npy', embeddings_2d)
print("Saved ✓")

"""### **Cell 13 — Determine Optimal Clusters**
* This cell tests different numbers of groups to find the most natural fit for your images.
* It uses the 'Silhouette Score' to measure how well-separated the groups are.
* It outputs a recommendation for the 'Optimal K' (number of clusters).
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

n_images = len(image_paths)
max_k = min(20, n_images // 2)
min_k = 2

print(f"Testing K from {min_k} to {max_k}...")

scores = {}
for k in range(min_k, max_k + 1):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(embeddings_32d)
    score = silhouette_score(embeddings_32d, labels, metric='euclidean')
    scores[k] = score
    print(f"  K={k:2d}  silhouette={score:.4f}")

optimal_k = max(scores, key=scores.get)
print(f"\n✓ Optimal K = {optimal_k}  (score: {scores[optimal_k]:.4f})")

"""### **Cell 14 — Execute Final Clustering**
* This cell performs the final grouping of images based on the optimal number found previously.
* It uses the K-Means algorithm to assign every image a specific cluster ID.
* It outputs the final distribution of images across all generated groups.
"""

from sklearn.cluster import KMeans

print(f"Running final KMeans with K={optimal_k}...")

kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=20)
cluster_labels = kmeans.fit_predict(embeddings_32d)

# Build cluster → image paths mapping
clusters = {}
for idx, label in enumerate(cluster_labels):
    clusters.setdefault(label, []).append(image_paths[idx])

print(f"\nCluster distribution:")
for cid in sorted(clusters.keys()):
    print(f"  Cluster {cid:2d}: {len(clusters[cid]):3d} images")

# Save labels
np.save('/content/cluster_labels.npy', cluster_labels)
print("\nSaved cluster_labels.npy ✓")

"""### **Cell 15 — Analyze Foreground Dominance**
* This cell determines if a cluster is dominated by specific objects or broad backgrounds.
* It samples images from each group to check the signal strength of individual pixels.
* It outputs a label of 'FOREGROUND' or 'BACKGROUND' for every cluster.
"""

from sklearn.metrics.pairwise import cosine_similarity
import torch
from transformers import AutoImageProcessor, AutoModel
from PIL import Image

print("Computing FG/BG dominance per cluster...")

# We use the CLS vs patch token ratio as the FG/BG signal
# CLS-heavy = background/scene dominant
# Patch-heavy = foreground object dominant

def get_fg_bg_ratio(image_path):
    img = Image.open(image_path).convert('RGB')
    inputs = processor(images=img, return_tensors='pt')
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
    tokens = outputs.last_hidden_state
    cls_norm   = tokens[:, 0, :].norm(dim=-1).item()
    patch_norm = tokens[:, 1:, :].mean(dim=1).norm(dim=-1).item()
    ratio = patch_norm / (cls_norm + 1e-8)
    return ratio  # >1.0 = FG dominant, <1.0 = BG dominant

cluster_fg_bg = {}
for cid, paths in clusters.items():
    sample = paths[:min(5, len(paths))]  # sample up to 5 per cluster
    ratios = [get_fg_bg_ratio(p) for p in sample]
    avg_ratio = np.mean(ratios)
    dominance = "FOREGROUND" if avg_ratio >= 1.0 else "BACKGROUND"
    cluster_fg_bg[cid] = {"ratio": avg_ratio, "dominance": dominance}
    print(f"  Cluster {cid:2d}: ratio={avg_ratio:.3f}  → {dominance}")

"""### **Cell 16 — Generate Initial Metadata**
* This cell compiles all the clustering results into a single structured JSON file.
* It saves image counts, paths, and the dominance analysis for each group.
* It outputs a summary of the total images and clusters processed.
"""

import json

cluster_meta = {}
for cid in sorted(clusters.keys()):
    cluster_meta[str(cid)] = {
        "image_paths": clusters[cid],
        "count": len(clusters[cid]),
        "fg_bg_dominance": cluster_fg_bg[cid]["dominance"],
        "fg_bg_ratio": round(cluster_fg_bg[cid]["ratio"], 4)
    }

with open('/content/cluster_metadata.json', 'w') as f:
    json.dump(cluster_meta, f, indent=2)

print("Saved cluster_metadata.json ✓")
print(f"\nSummary:")
print(f"  Total images   : {len(image_paths)}")
print(f"  Total clusters : {optimal_k}")
fg_count = sum(1 for v in cluster_fg_bg.values() if v['dominance'] == 'FOREGROUND')
print(f"  FG clusters    : {fg_count}")
print(f"  BG clusters    : {optimal_k - fg_count}")

"""### **Cell 17 — Prepare Visualization Data**
* This cell loads all saved files and applies filters to prepare for visual reporting.
* It expects the metadata and coordinate files generated in Phase 3.
* It outputs the basic counts of images and clusters to be plotted.
"""

import numpy as np
import json
from pathlib import Path

embeddings    = np.load('/content/embeddings.npy')
embeddings_2d = np.load('/content/embeddings_2d.npy')
cluster_labels = np.load('/content/cluster_labels.npy')

with open('/content/cluster_metadata.json', 'r') as f:
    cluster_meta = json.load(f)

with open('/content/image_paths.txt', 'r') as f:
    image_paths = [line.strip() for line in f.readlines()]

# Remove failed zero-rows (same as Phase 3)
valid_mask = ~(embeddings == 0).all(axis=1)
embeddings    = embeddings[valid_mask]
embeddings_2d = embeddings_2d[valid_mask]
image_paths   = [p for p, v in zip(image_paths, valid_mask) if v]
cluster_labels = cluster_labels[valid_mask]

n_clusters = len(cluster_meta)
print(f"Images: {len(image_paths)}")
print(f"Clusters: {n_clusters}")

"""### **Cell 18 — Create Cluster Map**
* This cell generates a 2D scatter plot showing how images are grouped in space.
* It color-codes each dot based on its cluster ID to show group separation.
* It saves the resulting plot as a high-resolution PNG image.
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

colors = cm.get_cmap('tab20', n_clusters)

fig, ax = plt.subplots(figsize=(14, 10))

for cid in range(n_clusters):
    mask = cluster_labels == cid
    ax.scatter(
        embeddings_2d[mask, 0],
        embeddings_2d[mask, 1],
        c=[colors(cid)],
        label=f"C{cid} ({mask.sum()})",
        s=60,
        alpha=0.8,
        edgecolors='white',
        linewidths=0.4
    )

ax.set_title("DINOv2 Cluster Map (UMAP 2D)", fontsize=16, fontweight='bold')
ax.legend(bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=9)
ax.set_xlabel("UMAP-1")
ax.set_ylabel("UMAP-2")
plt.tight_layout()
plt.savefig('/content/cluster_scatter.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved cluster_scatter.png ✓")

"""### **Cell 19 — Generate Image Grids**
* This cell creates visual contact sheets showing a preview of images inside each cluster.
* It titles each grid with the cluster ID and the detected dominance type.
* It saves a separate PNG file for every cluster discovered.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from PIL import Image
import math

def show_cluster_grid(cid, paths, dominance, max_images=30):
    n = min(max_images, len(paths))
    cols = 4
    rows = math.ceil(n / cols)

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 3, rows * 3))
    axes = np.array(axes).flatten()

    color = "#2563EB" if dominance == "FOREGROUND" else "#16A34A"
    fig.suptitle(
        f"Cluster {cid}  |  {len(paths)} images  |  {dominance}",
        fontsize=14, fontweight='bold', color=color, y=1.01
    )

    for i, ax in enumerate(axes):
        if i < n:
            try:
                img = Image.open(paths[i]).convert('RGB')
                img.thumbnail((300, 300))
                ax.imshow(img)
                ax.set_title(Path(paths[i]).name[:16], fontsize=7)
            except:
                ax.set_facecolor('#1a1a1a')
                ax.text(0.5, 0.5, 'Error', ha='center',
                        va='center', transform=ax.transAxes, color='red')
        ax.axis('off')

    plt.tight_layout()
    plt.savefig(f'/content/cluster_{cid:02d}_grid.png',
                dpi=120, bbox_inches='tight')
    plt.show()
    plt.close()

print("Generating cluster grids...\n")
for cid_str, meta in cluster_meta.items():
    cid = int(cid_str)
    show_cluster_grid(
        cid,
        meta['image_paths'],
        meta['fg_bg_dominance']
    )

"""### **Cell 20 — Calculate Quality Scores**
* This cell computes mathematical quality metrics for each individual group.
* It measures 'Cohesion' (similarity within a group) and 'Silhouette' (separation from others).
* It outputs a 'GOOD', 'WEAK', or 'POOR' status for every cluster found.
"""

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import silhouette_samples

print("Computing per-cluster quality scores...\n")

# Silhouette score per sample
sample_scores = silhouette_samples(
    np.load('/content/embeddings_32d.npy')[valid_mask],
    cluster_labels
)

quality_report = {}
for cid_str, meta in cluster_meta.items():
    cid = int(cid_str)
    mask = cluster_labels == cid

    # Intra-cluster cosine similarity (cohesion)
    cluster_embs = embeddings[mask]
    if len(cluster_embs) > 1:
        sim_matrix = cosine_similarity(cluster_embs)
        np.fill_diagonal(sim_matrix, 0)
        avg_sim = sim_matrix.sum() / (len(cluster_embs) * (len(cluster_embs) - 1))
    else:
        avg_sim = 1.0

    # Average silhouette for this cluster
    avg_sil = sample_scores[mask].mean()

    quality_report[cid] = {
        "cohesion": round(float(avg_sim), 4),
        "silhouette": round(float(avg_sil), 4),
        "count": int(mask.sum()),
        "dominance": meta['fg_bg_dominance']
    }

    status = "✓ GOOD" if avg_sil > 0.3 else ("⚠ WEAK" if avg_sil > 0.1 else "✗ POOR")
    print(f"Cluster {cid:2d}: cohesion={avg_sim:.3f}  "
          f"silhouette={avg_sil:.3f}  {status}  "
          f"[{meta['fg_bg_dominance']}]  {mask.sum()} imgs")

# Overall score
overall = np.mean([v['silhouette'] for v in quality_report.values()])
print(f"\nOverall clustering quality: {overall:.4f}")
print("Interpretation: >0.5 excellent | 0.3–0.5 good | 0.1–0.3 fair | <0.1 poor")

"""### **Cell 21 — Flag Weak Clusters**
* This cell identifies any clusters that are too small or visually inconsistent.
* It warns the user if specific groups should be merged for better results.
* It outputs a final quality report JSON file for external review.
"""

print("Clusters needing attention:\n")

weak = [(cid, v) for cid, v in quality_report.items() if v['silhouette'] < 0.2]

if not weak:
    print("All clusters passed quality threshold ✓")
else:
    for cid, v in weak:
        print(f"  Cluster {cid}: silhouette={v['silhouette']:.3f} "
              f"— only {v['count']} images, consider merging")
    print(f"\nSuggestion: re-run Phase 3 Cell 3 with K={optimal_k - len(weak)} "
          f"if weak clusters have <3 images")

# Save quality report
with open('/content/quality_report.json', 'w') as f:
    json.dump(quality_report, f, indent=2)
print("\nSaved quality_report.json ✓")

"""### **Cell 22 — Inter-Cluster Similarity**
* This cell creates a heatmap showing how similar the discovered groups are to one another.
* It calculates the average 'centroid' of each cluster to compare them.
* It outputs a visual matrix that helps identify groups that are nearly identical.
"""

import seaborn as sns

# Compute centroid per cluster
centroids = []
for cid in range(n_clusters):
    mask = cluster_labels == cid
    centroids.append(embeddings[mask].mean(axis=0))
centroids = np.array(centroids)

centroid_sim = cosine_similarity(centroids)

fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(
    centroid_sim,
    annot=True, fmt='.2f',
    cmap='Blues',
    xticklabels=[f"C{i}" for i in range(n_clusters)],
    yticklabels=[f"C{i}" for i in range(n_clusters)],
    ax=ax,
    vmin=0, vmax=1
)
ax.set_title("Inter-Cluster Similarity (centroid cosine)", fontsize=13)
plt.tight_layout()
plt.savefig('/content/cluster_heatmap.png', dpi=130, bbox_inches='tight')
plt.show()
print("Saved cluster_heatmap.png ✓")

"""### **Cell 23 — Install CLIP Library**
* This cell installs the OpenAI CLIP model used for semantic image naming.
* It uses a direct link to the GitHub repository to get the latest version.
* This is used for labeling, while DINOv2 remains the core clustering tool.

# **PHASE 5**

<a name="phase5"></a>
## Phase 5: Semantic Naming and Metadata Generation
We use OpenAI CLIP and custom logic to assign human-readable labels (e.g., 'Nature', 'Travel') to each visual cluster.
"""

!pip install git+https://github.com/openai/CLIP.git -q
# We use CLIP here purely for NAME MATCHING, not for embeddings
# DINOv2 stays as our clustering backbone

"""### **Cell 24 — Load Naming Model**
* This cell loads the CLIP (ViT-B/32) model into memory on the GPU or CPU.
* It initializes the specific preprocessing steps required for CLIP's vision system.
* It outputs a confirmation that the naming engine is online.

OLD
"""

import clip
import torch
from PIL import Image
import numpy as np

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

clip_model, clip_preprocess = clip.load("ViT-B/32", device=device)
clip_model.eval()
print("CLIP loaded for naming ✓")

"""### **Cell 25 — Encode Label Vocabulary**
* This cell takes a list of 50+ human-readable labels and converts them into machine data.
* It expects a list of categories like 'Travel', 'Food', or 'Family'.
* It outputs encoded 'text features' that the AI will use to match against clusters.
"""

LABEL_VOCABULARY = [
    # People & social
    "people", "friends", "family", "portrait", "selfie",
    "wedding", "birthday party", "graduation", "crowd",

    # Animals
    "animals", "birds", "cats", "dogs", "wildlife",
    "insects", "fish", "horses",

    # Nature & scenery
    "nature", "landscape", "mountains", "beach", "ocean",
    "forest", "sunset", "sunrise", "sky", "clouds",
    "waterfall", "river", "desert", "snow", "flowers",
    "trees", "garden",

    # Urban & architecture
    "city", "buildings", "architecture", "street",
    "night city", "mosque", "church", "bridge", "market",

    # Food & objects
    "food", "drinks", "restaurant", "cooking",
    "cars", "vehicles", "motorcycles",

    # Events & travel
    "travel", "tourism", "monuments", "museum",
    "sports", "gym", "hiking", "camping",

    # Indoor & lifestyle
    "indoor", "home", "office", "shopping",
    "books", "art", "technology",

    # Abstract / unclear
    "screenshots", "documents", "text", "memes"
]

print(f"Vocabulary size: {len(LABEL_VOCABULARY)} labels")

# Pre-encode all text labels once (reused for every cluster)
with torch.no_grad():
    text_tokens = clip.tokenize(
        [f"a photo of {label}" for label in LABEL_VOCABULARY]
    ).to(device)
    text_features = clip_model.encode_text(text_tokens)
    text_features = text_features / text_features.norm(dim=-1, keepdim=True)

print("Text labels encoded ✓")

"""### **Cell 26 — Semantic Naming Logic**
* This cell compares each cluster's average image against the vocabulary to find the best name.
* It uses a confidence threshold to decide if a label is accurate enough to use.
* It outputs the final assigned name and a confidence rating (High/Medium/Low) for each group.
"""



from tqdm import tqdm
import json

CONFIDENCE_THRESHOLD = 0.15   # minimum score to accept a label
                               # below this → fallback name assigned
SAMPLE_PER_CLUSTER = 8        # images sampled per cluster for naming
                               # more = more accurate but slower

cluster_names = {}
fallback_counter = 1

print("Naming clusters...\n")

for cid_str, meta in cluster_meta.items():
    cid = int(cid_str)
    paths = meta['image_paths']

    # Sample up to SAMPLE_PER_CLUSTER images from this cluster
    sample_paths = paths[:min(SAMPLE_PER_CLUSTER, len(paths))]

    # Average label scores across sampled images
    all_scores = np.array([
        get_image_label_scores(p) for p in sample_paths
    ])
    avg_scores = all_scores.mean(axis=0)  # [num_labels]

    # Pick top label
    top_idx = avg_scores.argmax()
    top_score = avg_scores[top_idx]
    top_label = LABEL_VOCABULARY[top_idx]

    # Pick top 3 for display
    top3_idx = avg_scores.argsort()[-3:][::-1]
    top3 = [(LABEL_VOCABULARY[i], round(float(avg_scores[i]), 3)) for i in top3_idx]

    # Apply confidence threshold
    if top_score >= CONFIDENCE_THRESHOLD:
        name = top_label.title()
        confidence = "HIGH" if top_score > 0.35 else "MEDIUM"
    else:
        name = f"Cluster {fallback_counter}"
        fallback_counter += 1
        confidence = "LOW"

    cluster_names[cid_str] = {
        "name": name,
        "confidence": confidence,
        "top_score": round(float(top_score), 4),
        "top3_labels": top3,
        "fg_bg": meta['fg_bg_dominance'],
        "count": meta['count']
    }

    print(f"Cluster {cid:2d} → '{name}' "
          f"[{confidence}] score={top_score:.3f} | "
          f"top3: {top3} | {meta['count']} imgs")

print(f"\nFallback names assigned: {fallback_counter - 1}")

"""### **Cell 27 — Deduplicate Names**
* This cell checks if multiple clusters were assigned the same name (e.g., two 'Travel' groups).
* It automatically appends numbers to duplicates (e.g., 'Travel 1', 'Travel 2').
* It outputs a list of any clusters that required renaming for uniqueness.
"""

from collections import Counter

# Find duplicate names
name_counts = Counter(v['name'] for v in cluster_names.values())
duplicates = {name for name, count in name_counts.items()
              if count > 1 and not name.startswith("Cluster")}

if duplicates:
    print(f"Duplicate names found: {duplicates}")
    name_occurrence = {}
    for cid_str, info in cluster_names.items():
        name = info['name']
        if name in duplicates:
            name_occurrence[name] = name_occurrence.get(name, 0) + 1
            cluster_names[cid_str]['name'] = f"{name} {name_occurrence[name]}"
            print(f"  Cluster {cid_str}: renamed to '{cluster_names[cid_str]['name']}'")
else:
    print("No duplicate names — all clusters have unique names ✓")

"""### **Cell 28 — Finalize Metadata Files**
* This cell updates the master metadata files with the final names and confidence scores.
* It saves the results into 'cluster_names.json' and 'cluster_metadata_named.json'.
* It outputs a clean text summary of every cluster and its final human-readable title.
"""

# Update cluster_meta with final names
for cid_str, name_info in cluster_names.items():
    cluster_meta[cid_str]['name'] = name_info['name']
    cluster_meta[cid_str]['confidence'] = name_info['confidence']
    cluster_meta[cid_str]['top3_labels'] = name_info['top3_labels']

with open('/content/cluster_metadata_named.json', 'w') as f:
    json.dump(cluster_meta, f, indent=2)

with open('/content/cluster_names.json', 'w') as f:
    json.dump(cluster_names, f, indent=2)

print("Saved cluster_metadata_named.json ✓")
print("Saved cluster_names.json ✓")

print("\n── Final Cluster Names ──")
for cid_str, info in cluster_names.items():
    bar = "█" * int(info['top_score'] * 30)
    print(f"  C{int(cid_str):02d}  {info['name']:<22} "
          f"{bar} {info['top_score']:.3f} [{info['confidence']}]")

"""### **Cell 29 — Visual Gallery Summary**
* This cell creates a final overview grid showing sample photos for every named cluster.
* It color-codes titles by confidence: blue for High, yellow for Medium, and gray for Low.
* It saves the full summary as a PNG for quick reference.
"""

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from PIL import Image
from pathlib import Path
import math

PREVIEW_PER_CLUSTER = 4   # thumbnails shown per cluster in summary

n = len(cluster_names)
cols = 2
rows = math.ceil(n / cols)

fig = plt.figure(figsize=(cols * 10, rows * 3.5))
fig.suptitle("ClipGallery — Named Clusters", fontsize=18,
             fontweight='bold', y=1.01)

for idx, (cid_str, info) in enumerate(cluster_names.items()):
    paths = cluster_meta[cid_str]['image_paths']
    sample = paths[:PREVIEW_PER_CLUSTER]

    outer = gridspec.GridSpec(rows, cols, figure=fig,
                              hspace=0.5, wspace=0.3)
    inner = gridspec.GridSpecFromSubplotSpec(
        1, PREVIEW_PER_CLUSTER,
        subplot_spec=outer[idx],
        wspace=0.05
    )

    color = "#2563EB" if info['confidence'] == "HIGH" else (
            "#F59E0B" if info['confidence'] == "MEDIUM" else "#6B7280")

    for j, path in enumerate(sample):
        ax = fig.add_subplot(inner[j])
        try:
            img = Image.open(path).convert('RGB')
            img.thumbnail((200, 200))
            ax.imshow(img)
        except:
            ax.set_facecolor('#111')
        ax.axis('off')
        if j == 0:
            ax.set_title(
                f"{info['name']}\n{info['count']} photos",
                fontsize=10, fontweight='bold',
                color=color, loc='left', pad=4
            )

plt.savefig('/content/named_clusters_summary.png',
            dpi=130, bbox_inches='tight')
plt.show()
print("Saved named_clusters_summary.png ✓")

"""### **Cell 30 — Setup Incremental Processing**
* This cell initializes a 'state' file to track already processed images.
* It allows the system to add new photos later without re-running the entire clustering process.
* It outputs the count of current images and the next available cluster ID.

UPDATED
"""

UPDATED


import numpy as np
import json
import torch
import clip
from PIL import Image
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

embeddings     = np.load('/content/embeddings.npy')
cluster_labels = np.load('/content/cluster_labels.npy')
embeddings_32d = np.load('/content/embeddings_32d.npy')

with open('/content/cluster_metadata.json', 'r') as f:
    cluster_meta = json.load(f)

with open('/content/image_paths.txt', 'r') as f:
    image_paths = [line.strip() for line in f.readlines()]

valid_mask = ~(embeddings == 0).all(axis=1)
embeddings     = embeddings[valid_mask]
embeddings_32d = embeddings_32d[valid_mask]
image_paths    = [p for p, v in zip(image_paths, valid_mask) if v]
cluster_labels = cluster_labels[valid_mask]

clip_model, clip_preprocess = clip.load("ViT-B/32", device=device)
clip_model.eval()

print(f"Loaded {len(image_paths)} images, {len(cluster_meta)} clusters ✓")

"""### **Cell 31 — Detect Digital Content**
* This cell uses fast pixel rules to identify screenshots, documents, and memes.
* It analyzes image brightness, color variance, and aspect ratio.
* It outputs a percentage breakdown of your gallery's 'special' vs 'photo' content.
"""

import numpy as np
from PIL import Image, ImageStat

def classify_image_type(image_path):
    """
    Fast pixel-level pre-classifier. Returns:
    'screenshot'  — UI elements, status bars, high text density
    'document'    — scanned docs, receipts, white background + text
    'meme'        — image with large text overlay
    'wallpaper'   — high resolution, very wide aspect ratio
    'photo'       — normal camera photo (passes to CLIP naming)
    """
    try:
        img = Image.open(image_path).convert('RGB')
        w, h = img.size
        aspect = w / h

        # Convert to grayscale for analysis
        gray = img.convert('L')
        stat = ImageStat.Stat(gray)
        mean_brightness = stat.mean[0]
        std_brightness  = stat.stddev[0]

        # Rule 1 — Screenshot detection
        # Screenshots have exact device resolution ratios + very uniform edges
        common_ratios = [9/16, 9/19.5, 9/20, 9/21, 3/4, 2/3]
        is_ratio_match = any(abs(w/h - r) < 0.05 or abs(h/w - r) < 0.05
                            for r in common_ratios)

        # Check top/bottom strips for uniform color (status bar pattern)
        top_strip    = np.array(img.crop((0, 0, w, min(60, h//8))))
        bottom_strip = np.array(img.crop((0, max(0, h - 60), w, h)))
        top_uniform    = top_strip.std() < 18
        bottom_uniform = bottom_strip.std() < 18

        if is_ratio_match and (top_uniform or bottom_uniform) and std_brightness < 70:
            return 'screenshot'

        # Rule 2 — Document detection
        # Very bright background, low color variance, portrait orientation
        pixel_array = np.array(img)
        color_std = pixel_array.std(axis=(0,1)).mean()
        if mean_brightness > 210 and color_std < 30 and h > w:
            return 'document'

        # Rule 3 — Wallpaper detection
        # Very wide or very tall, high resolution
        if (aspect > 1.9 or aspect < 0.5) and (w * h > 2_000_000):
            return 'wallpaper'

        # Rule 4 — Meme detection
        # High contrast black/white regions + standard meme ratios
        white_ratio = (np.array(gray) > 240).mean()
        black_ratio = (np.array(gray) < 15).mean()
        if white_ratio > 0.25 and black_ratio > 0.05:
            return 'meme'

        return 'photo'

    except Exception:
        return 'photo'


# Test on all images
print("Pre-classifying image types...")
type_map = {}
type_counts = {}

for path in image_paths:
    img_type = classify_image_type(path)
    type_map[path] = img_type
    type_counts[img_type] = type_counts.get(img_type, 0) + 1

print("\nImage type distribution:")
for t, count in sorted(type_counts.items(), key=lambda x: -x[1]):
    pct = count / len(image_paths) * 100
    print(f"  {t:<12}: {count:4d} images ({pct:.1f}%)")

"""### **Cell 32 — Advanced Category Setup**
* This cell defines 47 specific gallery categories grouped by theme (People, Nature, etc.).
* It creates multiple descriptive phrases for each category to improve matching accuracy.
* It outputs a confirmation that the high-resolution category map is ready.
"""

# Comprehensive vocabulary based on real gallery research
# Categories: people, nature, food, urban, events, objects,
#             animals, travel, sports, lifestyle, digital content

GALLERY_CATEGORIES = {
    # ── People ──
    "Selfies":          ["a selfie", "a person taking selfie", "close up face selfie"],
    "Portraits":        ["a portrait photo", "a person's face", "headshot photo"],
    "Family":           ["family photo", "family together", "parents and children"],
    "Friends":          ["friends together", "group of friends", "people hanging out"],
    "Wedding":          ["wedding ceremony", "bride and groom", "wedding celebration"],
    "Kids & Babies":    ["baby photo", "child playing", "kids at school"],

    # ── Nature ──
    "Landscapes":       ["landscape photo", "scenic nature view", "open countryside"],
    "Mountains":        ["mountain scenery", "hiking mountains", "mountain peaks"],
    "Beach & Ocean":    ["beach photo", "ocean waves", "seaside view"],
    "Sunsets":          ["sunset photo", "sunrise sky", "golden hour sky"],
    "Forests":          ["forest path", "trees in forest", "woodland nature"],
    "Flowers":          ["flowers photo", "garden flowers", "blooming plants"],
    "Sky & Clouds":     ["cloudy sky", "blue sky clouds", "dramatic sky"],
    "Snow & Winter":    ["snow landscape", "winter scene", "snowy mountains"],

    # ── Animals ──
    "Cats":             ["cat photo", "kitten", "domestic cat"],
    "Dogs":             ["dog photo", "puppy", "pet dog"],
    "Birds":            ["bird photo", "flying birds", "wildlife birds"],
    "Wildlife":         ["wild animals", "wildlife safari", "animals in nature"],
    "Pets":             ["pet animal", "domestic pet", "animal companion"],

    # ── Food & Drink ──
    "Food":             ["food photo", "meal on plate", "delicious food"],
    "Desserts":         ["dessert photo", "cake sweets", "ice cream dessert"],
    "Drinks":           ["drinks photo", "coffee cup", "beverage glass"],
    "Cooking":          ["cooking in kitchen", "food preparation", "chef cooking"],

    # ── Urban & Architecture ──
    "City":             ["city street", "urban cityscape", "downtown buildings"],
    "Architecture":     ["building architecture", "architectural photo", "historic building"],
    "Night City":       ["city at night", "night lights city", "urban night scene"],
    "Mosque":           ["mosque architecture", "islamic building", "minaret"],
    "Markets":          ["market bazaar", "street market", "shopping market"],

    # ── Travel ──
    "Travel":           ["travel photo", "tourist attraction", "sightseeing travel"],
    "Monuments":        ["famous monument", "historical landmark", "tourist monument"],
    "Airports":         ["airport terminal", "airplane travel", "flight boarding"],

    # ── Events ──
    "Birthday":         ["birthday party", "birthday cake celebration", "party celebration"],
    "Graduation":       ["graduation ceremony", "academic graduation", "cap and gown"],
    "Sports Events":    ["sports event", "stadium crowd", "sports match"],
    "Concerts":         ["music concert", "live performance", "concert crowd"],

    # ── Sports & Fitness ──
    "Gym & Fitness":    ["gym workout", "fitness exercise", "weight training"],
    "Outdoor Sports":   ["outdoor sport activity", "cycling running", "outdoor exercise"],
    "Cricket":          ["cricket match", "cricket players", "cricket stadium"],
    "Football":         ["football match", "soccer game", "football players"],

    # ── Lifestyle & Indoor ──
    "Home & Interior":  ["home interior", "room decoration", "indoor home"],
    "Shopping":         ["shopping photo", "store shopping", "retail products"],
    "Books & Study":    ["books reading", "studying desk", "library books"],
    "Cars & Vehicles":  ["car photo", "vehicle automobile", "car on road"],

    # ── Digital Content ──
    "Screenshots":      ["phone screenshot", "mobile app screenshot", "screen capture"],
    "Documents":        ["document paper", "text document", "written paper"],
    "Memes":            ["internet meme", "meme image", "funny meme text"],
    "Wallpapers":       ["digital wallpaper", "abstract wallpaper", "artistic wallpaper"],
}

print(f"Total categories: {len(GALLERY_CATEGORIES)}")
print("Encoding category text embeddings...")

# Encode all candidate phrases and average them per category
category_embeddings = {}
with torch.no_grad():
    for category, phrases in GALLERY_CATEGORIES.items():
        tokens = clip.tokenize(phrases).to(device)
        feats  = clip_model.encode_text(tokens)
        feats  = feats / feats.norm(dim=-1, keepdim=True)
        category_embeddings[category] = feats.mean(dim=0).cpu().numpy()

print("Category embeddings ready ✓")

"""### **Cell 33 — Smart Naming Execution**
* This cell executes the naming logic, combining the digital content rules with CLIP similarity.
* It handles the logic for choosing when to use a rule-based name vs an AI-matched name.
* It outputs a progress bar and a visual score indicator for each cluster's name.
"""

from tqdm import tqdm

SIMILARITY_THRESHOLD = 0.20   # minimum cosine sim to accept a name
                               # anything below → fallback name
SAMPLE_PER_CLUSTER   = 10     # images to sample per cluster

category_names  = list(category_embeddings.keys())
category_matrix = np.array(list(category_embeddings.values()))  # [N_cats, 512]

def get_image_clip_embedding(image_path):
    """Get CLIP visual embedding for a single image."""
    try:
        img = Image.open(image_path).convert('RGB')
        tensor = clip_preprocess(img).unsqueeze(0).to(device)
        with torch.no_grad():
            feat = clip_model.encode_image(tensor)
            feat = feat / feat.norm(dim=-1, keepdim=True)
        return feat.squeeze().cpu().numpy()
    except:
        return None

def name_cluster(paths, pre_type_map):
    """
    Names a cluster using:
    1. Pre-type override (screenshots/documents/memes/wallpapers)
    2. CLIP cosine similarity for photos
    """
    # Check if majority of images are a special type
    types = [pre_type_map.get(p, 'photo') for p in paths]
    type_counts = {}
    for t in types:
        type_counts[t] = type_counts.get(t, 0) + 1
    majority_type = max(type_counts, key=type_counts.get)
    majority_pct  = type_counts[majority_type] / len(types)

    # If >60% are a special digital type, override immediately
    special_type_names = {
        'screenshot': ('Screenshots', 1.0),
        'document':   ('Documents',   1.0),
        'meme':       ('Memes',       1.0),
        'wallpaper':  ('Wallpapers',  1.0),
    }
    if majority_type in special_type_names and majority_pct > 0.60:
        name, score = special_type_names[majority_type]
        return name, score, "HIGH", []

    # CLIP cosine similarity naming for photos
    sample = paths[:min(SAMPLE_PER_CLUSTER, len(paths))]
    clip_embeddings = [get_image_clip_embedding(p) for p in sample]
    clip_embeddings = [e for e in clip_embeddings if e is not None]

    if not clip_embeddings:
        return None, 0.0, "LOW", []

    # Average visual embedding for the cluster
    avg_clip = np.mean(clip_embeddings, axis=0)
    avg_clip = avg_clip / (np.linalg.norm(avg_clip) + 1e-8)

    # Cosine similarity against all category embeddings
    sims = cosine_similarity([avg_clip], category_matrix)[0]  # [N_cats]

    top3_idx  = sims.argsort()[-3:][::-1]
    top_idx   = top3_idx[0]
    top_score = sims[top_idx]
    top_name  = category_names[top_idx]
    top3      = [(category_names[i], round(float(sims[i]), 3)) for i in top3_idx]

    if top_score >= SIMILARITY_THRESHOLD:
        confidence = "HIGH" if top_score > 0.28 else "MEDIUM"
        return top_name, float(top_score), confidence, top3
    else:
        return None, float(top_score), "LOW", top3


print("Naming all clusters...\n")
cluster_names = {}
fallback_idx  = 1

for cid_str, meta in tqdm(cluster_meta.items(), desc="Naming"):
    cid   = int(cid_str)
    paths = meta['image_paths']

    name, score, confidence, top3 = name_cluster(paths, type_map)

    if name is None:
        name = f"Cluster {fallback_idx}"
        fallback_idx += 1

    cluster_names[cid_str] = {
        "name":       name,
        "score":      round(score, 4),
        "confidence": confidence,
        "top3":       top3,
        "count":      len(paths),
        "fg_bg":      meta.get('fg_bg_dominance', 'UNKNOWN')
    }

    bar = "█" * int(score * 40)
    print(f"  C{cid:02d} → '{name:<22}' "
          f"score={score:.3f} [{confidence}] {bar}")

named_count = sum(1 for v in cluster_names.values()
                  if not v['name'].startswith('Cluster'))
print(f"\nNamed:    {named_count}/{len(cluster_names)}")
print(f"Fallback: {len(cluster_names) - named_count}/{len(cluster_names)}")

"""### **Cell 34 — Rename & Persist State**
* This cell performs final deduplication and packages all clustering data into a single pickle file.
* It creates a 'cluster_state.pkl' which acts as the 'brain' for future updates.
* It outputs the next cluster ID and a confirmation that the state is saved.
"""

from collections import Counter

name_counts = Counter(v['name'] for v in cluster_names.values())
duplicates  = {n for n, c in name_counts.items()
               if c > 1 and not n.startswith('Cluster')}

if duplicates:
    print(f"Deduplicating: {duplicates}")
    occurrence = {}
    for cid_str, info in cluster_names.items():
        n = info['name']
        if n in duplicates:
            occurrence[n] = occurrence.get(n, 0) + 1
            cluster_names[cid_str]['name'] = f"{n} {occurrence[n]}"
            print(f"  C{cid_str} → '{cluster_names[cid_str]['name']}'")
else:
    print("All names unique ✓")

"""### **Cell 35 — Cleanup Miscellaneous Images**
* This cell gathers any single images that didn't fit into a group into a 'Miscellaneous' cluster.
* It also picks up any images that failed feature extraction earlier in the process.
* It outputs an updated JSON file with the catch-all cluster included.
"""

import pickle

def compute_centroids(embeddings, cluster_labels, n_clusters):
    """Compute mean embedding per cluster."""
    centroids = {}
    for cid in range(n_clusters):
        mask = cluster_labels == cid
        if mask.sum() > 0:
            centroids[cid] = embeddings[mask].mean(axis=0)
    return centroids

# Build and save centroids
n_clusters = len(cluster_meta)
centroids  = compute_centroids(embeddings, cluster_labels, n_clusters)

# Persistent state object saved to disk
cluster_state = {
    'centroids':      centroids,          # {cid: np.array [384]}
    'cluster_names':  cluster_names,      # {cid_str: name info}
    'cluster_meta':   cluster_meta,       # {cid_str: metadata}
    'image_paths':    image_paths,        # all processed paths
    'embeddings':     embeddings,         # all embeddings
    'cluster_labels': cluster_labels,     # label per image
    'next_cluster_id': n_clusters,
    'next_fallback_idx': fallback_idx
}

with open('/content/cluster_state.pkl', 'wb') as f:
    pickle.dump(cluster_state, f)

print(f"Saved cluster_state.pkl ✓")
print(f"Centroids: {len(centroids)}")
print(f"Next cluster ID will be: {n_clusters}")


def add_new_images(new_image_paths,
                   dinov2_model, dinov2_processor,
                   state_path='/content/cluster_state.pkl',
                   match_threshold=0.75,
                   new_cluster_threshold=0.60):
    """
    Incrementally adds new images to existing clusters.

    match_threshold      — cosine sim above this → assign to existing cluster
    new_cluster_threshold — below this for ALL clusters → create new cluster
    """
    # Load persistent state
    with open(state_path, 'rb') as f:
        state = pickle.load(f)

    centroids      = state['centroids']
    cluster_labels = state['cluster_labels'].tolist()
    all_embeddings = list(state['embeddings'])
    all_paths      = list(state['image_paths'])
    cluster_meta   = state['cluster_meta']
    cluster_names  = state['cluster_names']
    next_cid       = state['next_cluster_id']
    fallback_idx   = state['next_fallback_idx']

    assigned_new  = []
    created_new   = []
    centroid_keys = sorted(centroids.keys())
    centroid_mat  = np.array([centroids[k] for k in centroid_keys])

    print(f"\nProcessing {len(new_image_paths)} new images...")

    for path in tqdm(new_image_paths, desc="Incremental"):
        if path in all_paths:
            print(f"  Skip (already processed): {Path(path).name}")
            continue

        # Extract DINOv2 embedding
        try:
            img    = Image.open(path).convert('RGB')
            inputs = dinov2_processor(images=img, return_tensors='pt')
            inputs = {k: v.to(device) for k, v in inputs.items()}
            with torch.no_grad():
                out = dinov2_model(**inputs)
            emb = out.last_hidden_state[:, 0, :] * 0.5 + \
                  out.last_hidden_state[:, 1:, :].mean(dim=1) * 0.5
            emb = torch.nn.functional.normalize(emb, dim=-1)
            emb = emb.squeeze().cpu().numpy()
        except Exception as e:
            print(f"  Failed: {Path(path).name} — {e}")
            continue

        # Compare against all cluster centroids
        sims   = cosine_similarity([emb], centroid_mat)[0]
        max_sim = sims.max()
        best_cid = centroid_keys[sims.argmax()]

        if max_sim >= match_threshold:
            # Assign to best matching existing cluster
            cluster_labels.append(best_cid)
            cluster_meta[str(best_cid)]['image_paths'].append(path)
            cluster_meta[str(best_cid)]['count'] += 1

            # Update centroid (running mean)
            old_n = cluster_meta[str(best_cid)]['count'] - 1
            centroids[best_cid] = (centroids[best_cid] * old_n + emb) / (old_n + 1)

            assigned_new.append((path, best_cid, max_sim))
            print(f"  ✓ '{Path(path).name}' → Cluster {best_cid} "
                  f"('{cluster_names[str(best_cid)]['name']}') sim={max_sim:.3f}")

        else:
            # Create new cluster
            new_cid     = next_cid
            next_cid   += 1
            cid_str     = str(new_cid)

            # Name it
            pre_type    = classify_image_type(path)
            name, score, conf, top3 = name_cluster([path], {path: pre_type})
            if name is None:
                name = f"Cluster {fallback_idx}"
                fallback_idx += 1

            centroids[new_cid] = emb
            cluster_labels.append(new_cid)
            cluster_meta[cid_str] = {
                'image_paths': [path],
                'count': 1,
                'name': name
            }
            cluster_names[cid_str] = {
                'name': name, 'score': score,
                'confidence': conf, 'top3': top3, 'count': 1
            }
            created_new.append((path, new_cid, name))
            print(f"  ★ '{Path(path).name}' → NEW cluster {new_cid} "
                  f"('{name}') best_sim={max_sim:.3f}")

        all_embeddings.append(emb)
        all_paths.append(path)

    # Save updated state back to disk
    state.update({
        'centroids':        centroids,
        'cluster_labels':   np.array(cluster_labels),
        'embeddings':       np.array(all_embeddings),
        'image_paths':      all_paths,
        'cluster_meta':     cluster_meta,
        'cluster_names':    cluster_names,
        'next_cluster_id':  next_cid,
        'next_fallback_idx': fallback_idx
    })
    with open(state_path, 'wb') as f:
        pickle.dump(state, f)

    print(f"\n── Incremental Summary ──")
    print(f"  Assigned to existing clusters : {len(assigned_new)}")
    print(f"  New clusters created          : {len(created_new)}")
    print(f"  Total clusters now            : {next_cid}")
    print(f"  State saved ✓")

    return assigned_new, created_new


print("\nadd_new_images() function ready.")
print("Usage: add_new_images(new_paths, dinov2_model, dinov2_processor)")

for cid_str, name_info in cluster_names.items():
    cluster_meta[cid_str]['name']       = name_info['name']
    cluster_meta[cid_str]['confidence'] = name_info['confidence']
    cluster_meta[cid_str]['top3']       = name_info.get('top3', [])

with open('/content/cluster_metadata_named.json', 'w') as f:
    json.dump(cluster_meta, f, indent=2)

with open('/content/cluster_names.json', 'w') as f:
    json.dump(cluster_names, f, indent=2)

print("Saved cluster_metadata_named.json ✓")
print("Saved cluster_names.json ✓")
print("\n── Final Named Clusters ──")
for cid_str, info in sorted(cluster_names.items(), key=lambda x: int(x[0])):
    conf_icon = "🟢" if info['confidence'] == "HIGH" else (
                "🟡" if info['confidence'] == "MEDIUM" else "🔴")
    print(f"  C{int(cid_str):02d}  {conf_icon}  {info['name']:<25} "
          f"score={info['score']:.3f}  {info['count']} imgs")

# ── Miscellaneous Cluster Setup ──
# Run this after Cell 7 in Phase 5

MISC_CLUSTER_ID  = -1
MISC_CLUSTER_KEY = "-1"

# Collect any images that failed extraction (zero-row embeddings in raw file)
raw_embeddings = np.load('/content/embeddings.npy')  # unfiltered
all_raw_paths  = []
with open('/content/image_paths.txt', 'r') as f:
    all_raw_paths = [line.strip() for line in f.readlines()]

failed_paths = [
    p for p, emb in zip(all_raw_paths, raw_embeddings)
    if (emb == 0).all()
]

# Also collect singleton clusters (only 1 image, couldn't form a real group)
singleton_paths = []
for cid_str, meta in cluster_meta.items():
    if meta['count'] == 1:
        singleton_paths.extend(meta['image_paths'])
        # Remove from their solo cluster
        del cluster_meta[cid_str]
        del cluster_names[cid_str]

misc_paths = failed_paths + singleton_paths

if misc_paths:
    cluster_meta[MISC_CLUSTER_KEY] = {
        'image_paths': misc_paths,
        'count':       len(misc_paths),
        'name':        'Miscellaneous',
        'confidence':  'N/A',
        'fg_bg_dominance': 'UNKNOWN'
    }
    cluster_names[MISC_CLUSTER_KEY] = {
        'name':       'Miscellaneous',
        'score':      0.0,
        'confidence': 'N/A',
        'count':      len(misc_paths)
    }
    print(f"Miscellaneous cluster: {len(misc_paths)} images")
    print(f"  Failed extractions : {len(failed_paths)}")
    print(f"  Singleton clusters : {len(singleton_paths)}")
else:
    print("No miscellaneous images — all images clustered cleanly ✓")

# Resave with misc included
with open('/content/cluster_metadata_named.json', 'w') as f:
    json.dump(cluster_meta, f, indent=2)
with open('/content/cluster_names.json', 'w') as f:
    json.dump(cluster_names, f, indent=2)

print("Updated metadata saved with Miscellaneous cluster ✓")

"""### **Cell 36 — Export Preparation**
* This cell installs the 'ONNX' tools required to convert the model for Android use.
* It expects the Python environment to allow shell command execution.
* It outputs installation logs for onnx, onnxruntime, and optimization tools.
"""



"""<a name="phase6"></a>
## Phase 6: ONNX Export and Mobile Optimization
The final stage involves exporting the DINOv2 model to ONNX, applying INT8 quantization, and benchmarking it for Android use.
"""

!pip install onnx onnxruntime onnxscript onnxsim onnxruntime-tools -q

"""### **Cell 37 — Reload Export Model**
* This cell reloads the DINOv2 model on the CPU specifically for mobile compatibility.
* It ensures the 'processor' and 'model' are in sync for the export phase.
* It outputs a confirmation that the CPU-based model is ready.
"""

import torch
import onnx
import onnxruntime as ort
import numpy as np
from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import os

device = torch.device('cpu')  # Export on CPU — matches Android target

# Reload DINOv2 on CPU for export
print("Loading DINOv2-small on CPU for export...")
processor = AutoImageProcessor.from_pretrained('facebook/dinov2-small')
model     = AutoModel.from_pretrained('facebook/dinov2-small')
model     = model.to(device)
model.eval()
print("Model loaded ✓")

"""### **Cell 38 — Create Android Wrapper**
* This cell wraps the DINOv2 model in a special class that outputs a single normalized vector.
* This simplifies the Android code, as the app only has to handle one input and one output.
* It outputs a confirmation of the 'Wrapper output shape' and normalization.
"""

import torch.nn as nn

class DINOv2EmbedderWrapper(nn.Module):
    """
    Wraps DINOv2-small to output a single L2-normalized 384-dim
    FG/BG-combined embedding per image.

    Input  : float32 [1, 3, 224, 224]  — normalized image tensor
    Output : float32 [1, 384]          — L2-normalized embedding
    """
    def __init__(self, dinov2_model, alpha=0.5):
        super().__init__()
        self.model = dinov2_model
        self.alpha = alpha   # FG/BG blend: 0=pure BG, 1=pure FG, 0.5=balanced

    def forward(self, pixel_values):
        outputs = self.model(pixel_values=pixel_values)
        tokens  = outputs.last_hidden_state      # [1, 257, 384]

        cls_token    = tokens[:, 0, :]           # [1, 384] — BG signal
        patch_avg    = tokens[:, 1:, :].mean(1)  # [1, 384] — FG signal

        combined = (1 - self.alpha) * cls_token + self.alpha * patch_avg
        combined = nn.functional.normalize(combined, dim=-1)  # L2 normalize
        return combined                          # [1, 384]


wrapper = DINOv2EmbedderWrapper(model, alpha=0.5)
wrapper.eval()

# Verify wrapper output
dummy  = torch.randn(1, 3, 224, 224)
with torch.no_grad():
    out = wrapper(dummy)

print(f"Wrapper output shape : {out.shape}")        # [1, 384]
print(f"Output norm (≈1.0)   : {out.norm():.4f}")  # should be ~1.0
print("Wrapper ready ✓")

"""### **Cell 39 — Export ONNX FP32**
* This cell converts the PyTorch model into the universal ONNX format using standard precision.
* It sets 'dynamic_axes' so the mobile app can process one or many images at once.
* It outputs the final file size of the high-precision model in MB.
"""

ONNX_FP32_PATH = '/content/dinov2_small_embedder_fp32.onnx'

dummy_input = torch.randn(1, 3, 224, 224)

print("Exporting to ONNX FP32...")
torch.onnx.export(
    wrapper,
    dummy_input,
    ONNX_FP32_PATH,
    input_names   = ['pixel_values'],
    output_names  = ['embedding'],
    opset_version = 14,
    dynamic_axes  = {
        'pixel_values': {0: 'batch'},
        'embedding':    {0: 'batch'}
    },
    do_constant_folding = True   # folds constants → smaller model
)
print(f"Exported ✓")
print(f"FP32 size: {os.path.getsize(ONNX_FP32_PATH) / 1e6:.1f} MB")

"""### **Cell 40 — Simplify Model Graph**
* This cell runs 'onnx-simplifier' to remove redundant operations from the model.
* It ensures the resulting file is as efficient as possible for a mobile processor.
* It outputs the size comparison between the original and simplified models.
"""

from onnxsim import simplify

print("Simplifying ONNX graph...")
model_onnx  = onnx.load(ONNX_FP32_PATH)
model_simp, check = simplify(model_onnx)

assert check, "Simplified model failed validation"

ONNX_SIMP_PATH = '/content/dinov2_small_embedder_simplified.onnx'
onnx.save(model_simp, ONNX_SIMP_PATH)

print(f"Simplified ✓")
print(f"Original size  : {os.path.getsize(ONNX_FP32_PATH) / 1e6:.1f} MB")
print(f"Simplified size: {os.path.getsize(ONNX_SIMP_PATH) / 1e6:.1f} MB")

"""### **Cell 41 — Apply INT8 Quantization**
* This cell compresses the model from 32-bit decimals to 8-bit integers.
* This reduces the model size by ~75% and speeds up inference on mobile CPUs.
* It outputs the final size reduction percentage and the path to the INT8 file.
"""

from onnxruntime.quantization import quantize_dynamic, QuantType

ONNX_INT8_PATH = '/content/dinov2_small_embedder_int8.onnx'

print("Quantizing to INT8...")
quantize_dynamic(
    model_input       = ONNX_SIMP_PATH,
    model_output      = ONNX_INT8_PATH,
    weight_type       = QuantType.QInt8,
    per_channel       = False,    # per-tensor = better Android CPU compat
)

print(f"INT8 quantization done ✓")
print(f"Simplified FP32 : {os.path.getsize(ONNX_SIMP_PATH) / 1e6:.1f} MB")
print(f"INT8 quantized  : {os.path.getsize(ONNX_INT8_PATH) / 1e6:.1f} MB")
print(f"Size reduction  : {(1 - os.path.getsize(ONNX_INT8_PATH)/os.path.getsize(ONNX_SIMP_PATH))*100:.1f}%")

"""### **Cell 42 — Accuracy Verification**
* This cell compares the accuracy of the tiny INT8 model against the full-size model.
* It calculates 'Cosine Similarity' between the two to ensure the compression didn't ruin results.
* It outputs a 'Safe to use on Android' checkmark if accuracy is high enough.
"""

import numpy as np

def run_onnx(model_path, input_array):
    sess = ort.InferenceSession(
        model_path,
        providers=['CPUExecutionProvider']
    )
    return sess.run(None, {'pixel_values': input_array})[0]

# Use 5 real images for comparison
test_paths = []
with open('/content/image_paths.txt', 'r') as f:
    test_paths = [l.strip() for l in f.readlines()][:5]

print("Comparing FP32 vs INT8 embeddings...\n")

max_diff   = 0
min_cosine = 1.0

for path in test_paths:
    img    = Image.open(path).convert('RGB')
    inputs = processor(images=img, return_tensors='np')
    arr    = inputs['pixel_values'].astype(np.float32)

    emb_fp32 = run_onnx(ONNX_SIMP_PATH, arr)
    emb_int8 = run_onnx(ONNX_INT8_PATH, arr)

    diff   = np.abs(emb_fp32 - emb_int8).max()
    cosine = float(np.dot(emb_fp32[0], emb_int8[0]))  # both L2 normalized

    max_diff   = max(max_diff, diff)
    min_cosine = min(min_cosine, cosine)

    print(f"  {path.split('/')[-1]:<30} "
          f"max_diff={diff:.5f}  cosine_sim={cosine:.5f}")

print(f"\nWorst case max diff   : {max_diff:.5f}  (< 0.01 = excellent)")
print(f"Worst case cosine sim : {min_cosine:.5f}  (> 0.99 = excellent)")

if min_cosine > 0.97:
    print("\n✓ INT8 model is accurate — safe to use on Android")
else:
    print("\n⚠ Cosine sim below 0.97 — use FP32 simplified model instead")

"""### **Cell 43 — Performance Benchmark**
* This cell simulates a mobile CPU to measure how many milliseconds it takes to process an image.
* It forces a 'single thread' environment to mimic a mid-range Android device.
* It outputs the average processing time per image and a total estimate for 100 photos.
"""

import time

sess_int8 = ort.InferenceSession(
    ONNX_INT8_PATH,
    providers=['CPUExecutionProvider']
)

# Force single thread to simulate mobile CPU
opts = ort.SessionOptions()
opts.intra_op_num_threads = 1   # Android typically uses 1-4 threads
opts.inter_op_num_threads = 1

sess_single = ort.InferenceSession(
    ONNX_INT8_PATH,
    sess_options = opts,
    providers    = ['CPUExecutionProvider']
)

# Warmup
dummy_arr = np.random.randn(1, 3, 224, 224).astype(np.float32)
for _ in range(3):
    sess_single.run(None, {'pixel_values': dummy_arr})

# Benchmark 20 runs
times = []
for _ in range(20):
    t0 = time.perf_counter()
    sess_single.run(None, {'pixel_values': dummy_arr})
    times.append((time.perf_counter() - t0) * 1000)

avg_ms = np.mean(times)
p95_ms = np.percentile(times, 95)

print(f"── Mobile CPU Inference Benchmark (single thread) ──")
print(f"  Average  : {avg_ms:.1f} ms per image")
print(f"  P95      : {p95_ms:.1f} ms per image")
print(f"  Expected on Android mid-range : {avg_ms * 1.8:.0f}–{avg_ms * 2.5:.0f} ms")
print(f"  100 images would take         : {avg_ms * 100 / 1000:.1f}s (Colab) "
      f"/ {avg_ms * 2.5 * 100 / 1000:.1f}s (Android)")

"""### **Cell 44 — Validate Model Structure**
* This cell performs a final structural check on the exported ONNX file.
* It verifies the names of the inputs and outputs that the developer must use in Android Studio.
* It outputs the expected variable names and data types (e.g., 'pixel_values').
"""

model_check = onnx.load(ONNX_INT8_PATH)
onnx.checker.check_model(model_check)

print("ONNX model structure valid ✓")
print(f"\nInputs:")
for inp in model_check.graph.input:
    shape = [d.dim_value for d in inp.type.tensor_type.shape.dim]
    print(f"  {inp.name}: float32{shape}")

print(f"\nOutputs:")
for out in model_check.graph.output:
    shape = [d.dim_value for d in out.type.tensor_type.shape.dim]
    print(f"  {out.name}: float32{shape}")

"""### **Cell 45 — Download for Android**
* This cell triggers a browser download for the final optimized mobile model.
* It provides instructions on where to place the file in the Android project structure.
* It outputs the specific variable updates needed in your Kotlin code.
"""

from google.colab import files

# Choose which model to download based on Cell 6 validation:
# If cosine_sim > 0.97 → download INT8 (smaller, faster)
# If cosine_sim < 0.97 → download simplified FP32

FINAL_MODEL = ONNX_INT8_PATH  # change to ONNX_SIMP_PATH if INT8 failed validation

final_size = os.path.getsize(FINAL_MODEL) / 1e6

print(f"Downloading: {FINAL_MODEL.split('/')[-1]}")
print(f"Size: {final_size:.1f} MB")
print(f"\nAfter download, place this file at:")
print(f"  app/src/main/assets/dinov2_small_embedder_int8.onnx")
print(f"\nThen update OnnxEmbedder.kt:")
print(f"  MODEL_FILE     = 'dinov2_small_embedder_int8.onnx'")
print(f"  EMBEDDING_DIM  = 384   (was 512 for CLIP)")
print(f"  Input name     = 'pixel_values'")
print(f"  Output name    = 'embedding'")

files.download(FINAL_MODEL)

"""### **Cell 46 — Save to Drive**
* This cell mounts your Google Drive and backs up all important project files.
* It saves models, state files, and quality reports to a dedicated folder.
* It outputs a list of every file successfully copied to your persistent storage.
"""

from google.colab import drive
drive.mount('/gdrive')

import shutil

DRIVE_FOLDER = '/gdrive/MyDrive/ClipGallery_AI_Model'
os.makedirs(DRIVE_FOLDER, exist_ok=True)

# Copy all important outputs
files_to_save = {
    ONNX_INT8_PATH:                     'dinov2_small_embedder_int8.onnx',
    ONNX_SIMP_PATH:                     'dinov2_small_embedder_fp32.onnx',
    '/content/cluster_state.pkl':        'cluster_state.pkl',
    '/content/cluster_names.json':       'cluster_names.json',
    '/content/cluster_metadata_named.json': 'cluster_metadata_named.json',
    '/content/quality_report.json':      'quality_report.json',
}

for src, dst in files_to_save.items():
    dest_path = os.path.join(DRIVE_FOLDER, dst)
    shutil.copy(src, dest_path)
    size = os.path.getsize(dest_path) / 1e6
    print(f"  ✓ {dst:<45} {size:.1f} MB")

print(f"\nAll files saved to Google Drive: {DRIVE_FOLDER}")

"""METADATA ISSUE SOLVING"""

!pip install nbstripout
!nbstripout gallery_images_clustering_efficient_model.ipynb

import json
import os

filename = '/content/gallery_images_clustering_efficient_model.ipynb'

if not os.path.exists(filename):
    print(f"❌ Error: '{filename}' not found.")
    print("\n1. Download this notebook: File > Download > Download .ipynb")
    print(f"2. Rename it to '{filename}' and upload it to the folder icon on the left.")
else:
    with open(filename, 'r', encoding='utf-8') as f:
        notebook = json.load(f)

    modified = False

    # 1. Remove from global metadata
    if 'metadata' in notebook and 'widgets' in notebook['metadata']:
        del notebook['metadata']['widgets']
        modified = True
        print("✓ Removed widgets from global metadata.")

    # 2. Scrape all cells for hidden widget metadata
    for i, cell in enumerate(notebook.get('cells', [])):
        if 'metadata' in cell and 'widgets' in cell['metadata']:
            del cell['metadata']['widgets']
            modified = True
            print(f"✓ Removed widgets from cell {i} metadata.")

    if modified:
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(notebook, f, indent=1)
        print("\n✅ SUCCESS: The file on disk has been cleaned.")
        print("👉 IMPORTANT: Now right-click the file in the left sidebar, DOWNLOAD it, and upload THAT file to GitHub.")
    else:
        print("ℹ️ No widget metadata found. The file was already clean.")